
/*
 *  DISCLAIMER
 *
 *  Copyright © 2020, Alvaro Gomes Sobral Barcellos,
 *
 *  Permission is hereby granted, free of charge, to any person obtaining
 *  a copy of this software and associated documentation files (the
 *  "Software"), to deal in the Software without restriction, including
 *  without limitation the rights to use, copy, modify, merge, publish,
 *  distribute, sublicense, and/or sell copies of the Software, and to
 *  permit persons to whom the Software is furnished to do so, subject to
 *  the following conditions:
 *
 *  The above copyright notice and this permission notice shall be
 *  included in all copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 *  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 *  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 *  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 *  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 *  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 */

 disclaimer : 
 .ascii "DISCLAIMER this software is provided \"AS IS\".\n"
 .ascii "Copyright © 2020, Alvaro Gomes Sobral Barcellos,\n"
 .ascii "Licence Creative Commons,f8f98284-589e-4290-867c-0ac3824721ac,\n"
 .ascii "Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)\n"
 prompt : ; 4
 .ascii " OK\n"
 undef: ; 12
 .ascii " undefined?\n"
 roullete: ; 37, Pascal
 .word  0
 .word 32, 15, 19,  4, 21,  2, 25, 17, 34 
 .word  6, 27, 13, 36, 11, 30,  8, 23, 10
 .word  5, 24, 16, 33,  1, 20, 14, 31,  9
 .word 22, 18, 29,  7, 28, 12, 35,  3, 26
 
